"""modify models

Revision ID: 6d57981f2702
Revises: cf5e763d2877
Create Date: 2025-04-10 19:44:25.265886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d57981f2702'
down_revision: Union[str, None] = 'cf5e763d2877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('campaigns', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('campaigns', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('campaigns', 'budget',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint('campaigns_owner_id_fkey', 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('campaigns', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key('campaigns_owner_id_fkey', 'campaigns', 'users', ['owner_id'], ['id'])
    op.alter_column('campaigns', 'budget',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('campaigns', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('campaigns', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('campaigns', 'is_active')
    # ### end Alembic commands ###
