"""redefine campaign models

Revision ID: cf5e763d2877
Revises: 3bdabe91daae
Create Date: 2025-04-10 18:43:02.463251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5e763d2877'
down_revision: Union[str, None] = '3bdabe91daae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'budget',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'budget',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
